language: node_js
before_script: make
script: make travis
env:
  global:
    - SAUCE_USERNAME=josh-fetch
    - SAUCE_ACCESS_KEY=c3d37f93-0c2e-4834-9da5-eddc0d8c6299
  matrix:
    - SAUCE_PLATFORM="Windows 7" SAUCE_BROWSER="googlechrome" SAUCE_VERSION=""
addons:
  sauce_connect: true
deploy:
  provider: npm
  email: matt@mattandre.ws
  api_key:
    secure: FcQZz0HCJhrz8FZyyfkuXj4cwoBP+PeQ7LzOVU1bG7v3kX7Z33n8glD+32QScT2Uu369exdjkk3mzCaCMsfZTTvRm9STnuJIrPtdB2/FwfaWiyJiB1oZ2UCd5UQM0zMiQrtg+gR8FUBBgi3GICOkzAqTbso+C7P2IJtvpP9RTTI=
  on:
    all_branches: true
    tags: true
    repo: github/fetch
